# Generated by Django 2.2.2 on 2019-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detour', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
