# Generated by Django 2.2.2 on 2019-06-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detour', '0002_auto_20190612_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Collection',
            new_name='Map',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.AddField(
            model_name='detour',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detours', to='detour.Map'),
        ),
    ]
